# Site settings
title:          Mateus Almeida
description:    "My personal website about programming and technology"
url:            "https://imsouza.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Mateus Almeida
  url:          https://github.com/imsouza
  email:        mateusalmeida0715@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

theme: tale

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
