# Site settings
title:          Mateus Almeida
description:    "Meu blog pessoal sobre programação, tecnologia e afins."
url:            "https://imsouza.github.io"
rtl: true

# Google Analytics
google_analytics: UA-143763992-1

# Author
author:
  name:         Mateus Almeida
  url:          https://github.com/imsouza
  email:        mateusalmeida0715@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

theme: tale

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

# Permalinks
permalink:      /:title
paginate:       8

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
